// <auto-generated />
using Linkedin.CashMachine.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Linkedin.CashMachine.Migrations
{
    [DbContext(typeof(CashMachineDbContext))]
    [Migration("20171101062728_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Linkedin.CashMachine.Entities.Bill", b =>
                {
                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Quantity");

                    b.HasKey("Value");

                    b.ToTable("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
